name: translation-rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain>=0.2.0
      - langchain_community
      - langchain_fireworks
      - chromadb
      - python-dotenv
