name: translation-rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain>=0.2.0
      - langchain_community
      - langchain_fireworks
      - langchain_chroma
      - chromadb
      - python-dotenv
      - jinja2
      - langdetect
      - sentence-transformers  # For better embeddings
      - huggingface-hub        # HuggingFace integration
      - transformers           # For HuggingFace embeddings
      - loguru                 # Simple logging utility
